export const GET_DANH_SACH_GHE = 'GET_DANH_SACH_GHE'
export const SET_GHE_DANG_DAT = 'SET_GHE_DA_DAT'
export const DAT_VE = 'DAT_VE'
export const DAT_VE_HOAN_TAT = 'DAT_VE_HOAN_TAT'
export const CHUYEN_TAB = 'CHUYEN_TAB'
export const CHANGE_TAB = 'CHANGE_TAB'