export const DANG_NHAP_ACTION = 'GET_INFO_USER'
export const SET_THONG_TIN_NGUOI_DUNG = 'SET_THONG_TIN_NGUOI_DUNG'
export const LAY_DANH_SACH_NGUOI_DUNG = 'LAY_DANH_SACH_NGUOI_DUNG'
export const THONG_TIN_TAI_KHOAN = 'THONG_TIN_TAI_KHOAN'