export const GET_ARRFILM_SLICK = 'GET_ARRFILM_SLICK'
export const GET_ARRFILM_DANG_CHIEU = 'GET_ARRFILM_DANG_CHIEU'
export const GET_ARRFILM_SAP_CHIEU = 'GET_ARRFILM_SAP_CHIEU'
export const GET_CHI_TIET_PHIM = 'GET_CHI_TIET_PHIM'